version: 2.1

commands:
  check_system:
    steps:
      - run:
          name: Check system
          command: df -h && echo "Cores = $(nproc --all)"
  setup_env:
    steps:
      - run:
          name: Setup environment
          command: |
            apt-get --quiet update && apt-get --quiet install git aria2 apt-utils openjdk-8-jdk -y
            echo "Configuring git"
            git config --global user.email "$GIT_EMAIL"
            git config --global user.name "Teguhpunya"
            git config --global credential.helper "cache --timeout=7200"
            echo "git identity setup successfully!"
            git clone https://gitlab.com/teguhpunya-projects/scripts.git --depth=1 --branch master
            ./scripts/setup/android_build_env.sh
            ./scripts/setup/install_android_sdk.sh

  setup_repos:
    steps:
      - run:
          name: Setup repos
          command: |
            echo "Current dir = $(pwd)"
            git clone https://gitlab.com/Teguhpunya/orangefox-sync.git sync
            cd sync
            ./get_fox_10.sh
            cd fox_10.0
            git clone https://gitlab.com/Teguhpunya/ginkgo.git -b fox_10 device/xiaomi/ginkgo
            rm -rf bootable/recovery
            git clone --recurse-submodules https://gitlab.com/OrangeFox/bootable/Recovery.git -b $FOX_BRANCH bootable/recovery
            rm -rf vendor/recovery
            git clone https://gitlab.com/OrangeFox/vendor/recovery.git -b $FOX_BRANCH vendor/recovery


  build:
    steps:
      - run:
          name: Build
          command: |
            cd sync/fox_10.0
            . build/envsetup.sh
            export LC_ALL="C"
            export ALLOW_MISSING_DEPENDENCIES=true
            export FILES="$PWD/out/target/product/ginkgo/OrangeFox-$FOX_VERSION-$FOX_BUILD_TYPE-$FOX_BUILD_DEVICE.zip"
            cp -f $PWD/device/xiaomi/ginkgo/teguhpunya.png $PWD/bootable/recovery/gui/theme/portrait_hdpi/images/Default/About/maintainer.png
            rm -rf ./out
            source device/xiaomi/ginkgo/vendorsetup.sh
            make clean
            lunch omni_ginkgo-eng && mka recoveryimage
            BUILDFILE=$(find $(pwd)/out/target/product/ginkgo/OrangeFox* 2>/dev/null)
            UPLOAD_PATH=$(pwd)/out/target/product/ginkgo/upload/
            mkdir $UPLOAD_PATH && cp $BUILDFILE $UPLOAD_PATH

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202107-02

  docker-executor:
    docker:
      - image: ubuntu:focal

jobs:
  build-ofox:
    executor: machine-executor
    working_directory: ~/project
    environment:
      DEBIAN_FRONTEND: noninteractive
      FOX_BRANCH: fox_10.0
      FOX_VERSION: R11.1
      FOX_BUILD_TYPE: Stable
      FOX_VARIANT: A10
      OF_MAINTAINER: Teguhpunya
      FOX_BUILD_DEVICE: ginkgo
    steps:
      - checkout
      - check_system
      - setup_env
      - setup_repos
      - build
      - store_artifacts:
          path: sync/fox_10.0/out/target/product/ginkgo/upload/

workflows:
  build-orangefox:
    jobs:
      - build-ofox:
          context: orangefox
