version: 2.1

commands:
  check_system:
    steps:
      - run:
          name: Check system
          command: df -h && echo "Cores = $(nproc --all)"
  setup_env:
    steps:
      - run:
          name: Setup environment
          command: |
            apt-get --quiet update && apt-get --quiet install git aria2 apt-utils openjdk-8-jdk -y
            echo "Configuring git"
            git config --global user.email "$GIT_EMAIL"
            git config --global user.name "Teguhpunya"
            git config --global credential.helper "cache --timeout=7200"
            echo "git identity setup successfully!"
            git clone https://gitlab.com/teguhpunya-projects/scripts.git --depth=1 --branch circleci
            bash scripts/setup/android_build_env.sh >/dev/null
            bash scripts/setup/install_android_sdk.sh >/dev/null

  setup_repos:
    steps:
      - run:
          name: Setup repos
          command: |
            echo "Current dir = $(pwd)"
            mkdir -p OrangeFox_10
            cd OrangeFox_10
            git clone https://gitlab.com/OrangeFox/sync.git
            cd sync
            export FOX_BRANCH="fox_10.0"
            export TWRP_BRANCH="twrp-10.0"
            export DEVICE_BRANCH="android-10"
            export BASE_DIR="$PWD"
            export MANIFEST_DIR="$BASE_DIR/$FOX_BRANCH"
            export MANIFEST_BUILD_DIR="$MANIFEST_DIR/build"
            export PATCH_FILE="$BASE_DIR/patch-manifest-$FOX_BRANCH.diff"
            export MIN_MANIFEST="git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git"            
            echo "-- The new build system will be located in \"$MANIFEST_DIR\""
            mkdir -p $MANIFEST_DIR && cd $MANIFEST_DIR
            repo init --depth=1 -u $MIN_MANIFEST -b $TWRP_BRANCH
            echo "-- Syncing the $TWRP_BRANCH minimal manifest repo ..."
            repo sync -j$(nproc --all) --force-sync
            patch -p1 < $PATCH_FILE
            cd $MANIFEST_DIR/
            echo "-- Cloning qcom common ..."
            git clone https://github.com/TeamWin/android_device_qcom_common -b $DEVICE_BRANCH device/qcom/common
            echo "-- Cloning twrp-common ..."
            git clone https://github.com/TeamWin/android_device_qcom_twrp-common -b $DEVICE_BRANCH device/qcom/twrp-common
            rm -rf $MANIFEST_DIR/bootable/recovery
            git clone --recurse-submodules https://gitlab.com/OrangeFox/bootable/Recovery.git -b $FOX_BRANCH $MANIFEST_DIR/bootable/recovery
            rm -rf $MANIFEST_DIR/vendor/recovery
            git clone https://gitlab.com/OrangeFox/vendor/recovery.git -b $FOX_BRANCH $MANIFEST_DIR/vendor/recovery
            echo "Clonning dt, current dir = $(pwd)"
            git clone https://gitlab.com/Teguhpunya/ginkgo.git -b fox_10 --depth=1 $MANIFEST_DIR/device/xiaomi/ginkgo

  build:
    steps:
      - run:
          name: Build
          command: |
            cd $MANIFEST_DIR
            . build/envsetup.sh
            export LC_ALL="C"
            export ALLOW_MISSING_DEPENDENCIES=true
            export FOX_VERSION="R11.1_2"
            export FOX_BUILD_TYPE="Beta"
            export OF_MAINTAINER="Teguhpunya"
            export FOX_BUILD_DEVICE="ginkgo"
            export FILES="$PWD/out/target/product/ginkgo/OrangeFox-$FOX_VERSION-$FOX_BUILD_TYPE-$FOX_BUILD_DEVICE.zip"
            cp -f $PWD/device/xiaomi/ginkgo/teguhpunya.png $PWD/bootable/recovery/gui/theme/portrait_hdpi/images/Default/About/maintainer.png
            rm -rf ./out
            source $MANIFEST_DIR/device/xiaomi/ginkgo/vendorsetup.sh
            make clean
            lunch omni_ginkgo-eng && mka recoveryimage
            BUILDFILE=$(find $(pwd)/out/target/product/ginkgo/OrangeFox* 2>/dev/null)
            UPLOAD_PATH=$(pwd)/out/target/product/ginkgo/upload/
            mkdir $UPLOAD_PATH && cp $BUILDFILE $UPLOAD_PATH

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202010-01

  docker-executor:
    docker:
      - image: ubuntu:focal

jobs:
  build-ofox:
    executor: docker-executor
    working_directory: ~/project
    environment:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - checkout
      - check_system
      - setup_env
      - setup_repos
      - build
      - store_artifacts:
          path: out/target/product/ginkgo/upload/

workflows:
  build-orangefox:
    jobs:
      - build-ofox:
          context: orangefox
