version: 2.1

commands:
  check_system:
    steps:
      - run:
          name: Check system
          command: df -h && echo "Cores = $(nproc --all)"
  setup_env:
    steps:
      - run:
          name: Setup environment
          command: |
            sudo apt-get --quiet update && sudo apt-get --quiet install git aria2 apt-utils -y
            echo "Configuring git"
            git config --global user.email "$GIT_EMAIL"
            git config --global user.name "Teguhpunya"
            git config --global credential.helper "cache --timeout=7200"
            echo "git identity setup successfully!"
            git clone https://gitlab.com/teguhpunya-projects/scripts.git --depth=1 --branch circleci
            sudo -s bash scripts/setup/android_build_env.sh >/dev/null
            sudo -s bash scripts/setup/install_android_sdk.sh >/dev/null
  setup_repos:
    steps:
      - run:
          name: Setup repos
          command: |
            repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b $TWRP_BRANCH
            repo sync -j$(nproc --all) --force-sync >/dev/null
            git clone https://pop:$GITLAB_PASS@gitlab.com/Teguhpunya/android_device_xiaomi_ginkgo.git -b wp-twrp --depth=1 device/xiaomi/ginkgo
  build:
    steps:
      - run:
          name: Build
          command: |
            ./device/xiaomi/ginkgo/teskrip.sh
            BUILDFILE=$(find $(pwd)/out/target/product/ginkgo/*.img 2>/dev/null)
            UPLOAD_PATH=$(pwd)/out/target/product/ginkgo/upload/
            mkdir $UPLOAD_PATH && cp $BUILDFILE $UPLOAD_PATH

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: ~/project
    environment:
      DEBIAN_FRONTEND: noninteractive
      TWRP_BRANCH: twrp-10.0

jobs:
  build-with-machine:
    executor: machine-executor
    steps:
      - checkout
      - check_system
      - setup_env
      - setup_repos
      - build
      - store_artifacts:
          path: out/target/product/ginkgo/upload/

workflows:
  build-with-machine:
    jobs:
      - build-with-machine:
          context: orangefox
